---
title: "|-"
  Data wrangling:
   Regional temperature dataset
output:
  html_notebook:
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_float: yes
  html_document:
    date: "`r format(Sys.time(), '%d %B, %Y')`"
    highlight: textmate
    theme: spacelab
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


Michael Stölzle (michael.stoelzle@hydro.uni-freiburg.de)



# Introduction
 
Load or install required packages. 

##### Aim

```{r cars, message=TRUE, warning=TRUE}
if (!require(tidyverse))  install.packages(tidyverse) 

library(tidyverse, quietly=TRUE)
library(viridis)

df
gf <- read_tsv('/Users/modchembp/Dropbox/IHF/Lehre/Datenkurs_2018/geo_locs.txt')
af <- inner_join(df,gf)
#knitr::kable(head(af))

```

# Data wrangling
## Load data

Now you can load the large data file:
```{r pressure, echo=TRUE}

 af2 <- af %>% 
   filter(date>="1987-01-01") %>% 
   group_by(station) %>% 
   summarise(m=mean(TMK,na.rm=T), e=mean(elev), lon=mean(lon))  %>% 
   arrange(m) 

   ggplot(data=af2 , aes(x =m , y =reorder(factor(station),e)  )) + 
   geom_point(size=4,alpha=.9, aes(fill=m),pch=21) + 
   theme_classic() + 
   scale_fill_viridis(option="D", name="", begin=0, end=1)+
   theme(panel.grid.major.y = element_line(linetype=3, size=.2)) +
   xlab("Mittlere Temperatur 1987-2016")


```

**Figure**: Dotplot showing variation in mean temperature across Baden-Württemberg.
